language: python
python:
  - "3.5"
  - "3.6"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=system

install:
  - pip install coverage
  - python setup.py install
script:
  - nosetests -s -v --with-coverage tests.$TEST_SUITE
after_success:
    - bash <(curl -s https://codecov.io/bash)