language: python
python:
  - "3.5"
  - "3.6"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=system

install:
  - pwd
  - python setup.py install
script:
  - python -m unittest
branches:
  only:
    - master