language: python
python:
  - "3.6"
  - "3.7"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=system

install:
  - pip install -e .[test]
script:
  - pip list
  - pytest --cov=gama -sv -n 4 tests/$TEST_SUITE/
after_success:
 - bash <(curl -s https://codecov.io/bash)