language: python
python:
  - "3.5"
  - "3.6"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=system

branches:
  only:
    - master
    - development

install:
  - pwd
  - python setup.py install
script:
  - python -m unittest
after_success:
    - bash <(curl -s https://codecov.io/bash)
