language: python
python:
  - "3.6"
  - "3.7"
env:
  - JOB=test SUITE=unit
  - JOB=test SUITE=system

# Perform pre-commit checks only once:
jobs:
  include:
  - env: JOB=check
  - env: JOB=deploy
    if: branch = master

install:
  - ./ci_scripts/install.sh
script:
  - ./ci_scripts/script.sh
after_success:
 - ./ci_scripts/after_success.sh

before_deploy:
 - ./ci_scripts/build_docs.sh
deploy:
  provider: pages
  local_dir: docs/build
  edge: true
  token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $JOB = deploy
