language: python
python:
  - "3.6"
  - "3.7"

env:
  - TEST_SUITE=unit
  - TEST_SUITE=system

install:
  - pip install -e '.[develop]'
script:
  - pip list
  - pytest --cov=gama -sv tests.$TEST_SUITE
after_success:
 - bash <(curl -s https://codecov.io/bash)